
data = [{"name":"car", "verb":"entered", "frame":601},
{"name":"car", "verb":"entered", "frame":601},
{"name":"car", "verb":"entered", "frame":601},
{"name":"car", "verb":"entered", "frame":611},
{"name":"car", "verb":"exited", "frame":612},
{"name":"car", "verb":"entered", "frame":613},
{"name":"car", "verb":"entered", "frame":614},
{"name":"car", "verb":"entered", "frame":301},
{"name":"car", "verb":"exited", "frame":304},
{"name":"car", "verb":"entered", "frame":309},
{"name":"car", "verb":"exited", "frame":310},
{"name":"car", "verb":"entered", "frame":311},
{"name":"car", "verb":"exited", "frame":312},
{"name":"car", "verb":"entered", "frame":315},
{"name":"car", "verb":"exited", "frame":316},
{"name":"truck", "verb":"entered", "frame":319},
{"name":"truck", "verb":"entered", "frame":320},
{"name":"truck", "verb":"exited", "frame":323},
{"name":"truck", "verb":"entered", "frame":324},
{"name":"car", "verb":"entered", "frame":326},
{"name":"truck", "verb":"exited", "frame":328},
{"name":"truck", "verb":"exited", "frame":328},
{"name":"truck", "verb":"entered", "frame":329},
{"name":"truck", "verb":"entered", "frame":329},
{"name":"car", "verb":"exited", "frame":329},
{"name":"car", "verb":"entered", "frame":330},
{"name":"car", "verb":"exited", "frame":333},
{"name":"truck", "verb":"exited", "frame":336},
{"name":"truck", "verb":"entered", "frame":338},
{"name":"car", "verb":"entered", "frame":339},
{"name":"truck", "verb":"exited", "frame":339},
{"name":"truck", "verb":"exited", "frame":339},
{"name":"truck", "verb":"entered", "frame":340},
{"name":"truck", "verb":"entered", "frame":340},
{"name":"bus", "verb":"entered", "frame":341},
{"name":"car", "verb":"exited", "frame":341},
{"name":"car", "verb":"entered", "frame":345},
{"name":"bus", "verb":"exited", "frame":345},
{"name":"car", "verb":"exited", "frame":348},
{"name":"car", "verb":"entered", "frame":349},
{"name":"person", "verb":"entered", "frame":352},
{"name":"car", "verb":"exited", "frame":352},
{"name":"car", "verb":"entered", "frame":354},
{"name":"motorbike", "verb":"entered", "frame":354},
{"name":"truck", "verb":"exited", "frame":354},
{"name":"truck", "verb":"exited", "frame":354},
{"name":"truck", "verb":"entered", "frame":355},
{"name":"truck", "verb":"entered", "frame":355},
{"name":"car", "verb":"exited", "frame":355},
{"name":"motorbike", "verb":"exited", "frame":355},
{"name":"car", "verb":"entered", "frame":356},
{"name":"motorbike", "verb":"entered", "frame":356},
{"name":"person", "verb":"exited", "frame":356},
{"name":"truck", "verb":"exited", "frame":356},
{"name":"truck", "verb":"exited", "frame":356},
{"name":"person", "verb":"entered", "frame":357},
{"name":"truck", "verb":"entered", "frame":357},
{"name":"truck", "verb":"entered", "frame":357},
{"name":"car", "verb":"exited", "frame":357},
{"name":"car", "verb":"entered", "frame":358},
{"name":"person", "verb":"exited", "frame":358},
{"name":"truck", "verb":"exited", "frame":358},
{"name":"truck", "verb":"exited", "frame":358},
{"name":"truck", "verb":"entered", "frame":359},
{"name":"truck", "verb":"entered", "frame":360},
{"name":"car", "verb":"exited", "frame":360},
{"name":"motorbike", "verb":"exited", "frame":360},
{"name":"car", "verb":"entered", "frame":361},
{"name":"motorbike", "verb":"entered", "frame":361},
{"name":"person", "verb":"entered", "frame":361},
{"name":"truck", "verb":"exited", "frame":361},
{"name":"motorbike", "verb":"exited", "frame":362},
{"name":"motorbike", "verb":"entered", "frame":363},
{"name":"person", "verb":"exited", "frame":363},
{"name":"truck", "verb":"exited", "frame":363},
{"name":"car", "verb":"exited", "frame":364},
{"name":"car", "verb":"entered", "frame":365},
{"name":"car", "verb":"entered", "frame":366},
{"name":"motorbike", "verb":"exited", "frame":366},
{"name":"car", "verb":"exited", "frame":367},
{"name":"motorbike", "verb":"entered", "frame":367},
{"name":"person", "verb":"entered", "frame":367},
{"name":"car", "verb":"entered", "frame":368},
{"name":"car", "verb":"entered", "frame":368},
{"name":"motorbike", "verb":"exited", "frame":368},
{"name":"car", "verb":"exited", "frame":369},
{"name":"car", "verb":"exited", "frame":369},
{"name":"person", "verb":"exited", "frame":371},
{"name":"person", "verb":"entered", "frame":372},
{"name":"car", "verb":"exited", "frame":372},
{"name":"car", "verb":"entered", "frame":373},
{"name":"car", "verb":"entered", "frame":374},
{"name":"person", "verb":"exited", "frame":377},
{"name":"person", "verb":"entered", "frame":378},
{"name":"motorbike", "verb":"entered", "frame":380},
{"name":"motorbike", "verb":"exited", "frame":383},
{"name":"person", "verb":"exited", "frame":383},
{"name":"motorbike", "verb":"entered", "frame":386},
{"name":"person", "verb":"entered", "frame":386},
{"name":"car", "verb":"exited", "frame":387},
{"name":"motorbike", "verb":"exited", "frame":387},
{"name":"person", "verb":"exited", "frame":387},
{"name":"motorbike", "verb":"entered", "frame":392},
{"name":"motorbike", "verb":"exited", "frame":393},
{"name":"car", "verb":"entered", "frame":394},
{"name":"motorbike", "verb":"entered", "frame":394},
{"name":"motorbike", "verb":"exited", "frame":396},
{"name":"car", "verb":"entered", "frame":398},
{"name":"car", "verb":"exited", "frame":399},
{"name":"car", "verb":"exited", "frame":400},
{"name":"car", "verb":"entered", "frame":401},
{"name":"person", "verb":"entered", "frame":401},
{"name":"car", "verb":"exited", "frame":402},
{"name":"person", "verb":"exited", "frame":402},
{"name":"car", "verb":"exited", "frame":405},
{"name":"car", "verb":"entered", "frame":406},
{"name":"car", "verb":"entered", "frame":409},
{"name":"motorbike", "verb":"entered", "frame":409},
{"name":"car", "verb":"exited", "frame":411},
{"name":"motorbike", "verb":"exited", "frame":411},
{"name":"truck", "verb":"entered", "frame":417},
{"name":"car", "verb":"exited", "frame":418},
{"name":"car", "verb":"entered", "frame":420},
{"name":"truck", "verb":"entered", "frame":420},
{"name":"car", "verb":"exited", "frame":422},
{"name":"car", "verb":"entered", "frame":423},
{"name":"truck", "verb":"exited", "frame":423},
{"name":"truck", "verb":"entered", "frame":425},
{"name":"truck", "verb":"exited", "frame":427},
{"name":"truck", "verb":"entered", "frame":428},
{"name":"truck", "verb":"exited", "frame":429},
{"name":"truck", "verb":"entered", "frame":430},
{"name":"truck", "verb":"exited", "frame":431},
{"name":"car", "verb":"exited", "frame":435},
{"name":"truck", "verb":"exited", "frame":443},
{"name":"truck", "verb":"entered", "frame":444},
{"name":"truck", "verb":"exited", "frame":446},
{"name":"truck", "verb":"entered", "frame":449},
{"name":"truck", "verb":"exited", "frame":450},
{"name":"car", "verb":"entered", "frame":462},
{"name":"car", "verb":"entered", "frame":466},
{"name":"car", "verb":"exited", "frame":467},
{"name":"car", "verb":"exited", "frame":467},
{"name":"car", "verb":"entered", "frame":469},
{"name":"car", "verb":"exited", "frame":470},
{"name":"car", "verb":"entered", "frame":471},
{"name":"car", "verb":"exited", "frame":472},
{"name":"car", "verb":"entered", "frame":480},
{"name":"car", "verb":"exited", "frame":481},
{"name":"car", "verb":"entered", "frame":500},
{"name":"car", "verb":"exited", "frame":501},
{"name":"car", "verb":"entered", "frame":502},
{"name":"car", "verb":"exited", "frame":506},
{"name":"car", "verb":"entered", "frame":509},
{"name":"car", "verb":"exited", "frame":521},
{"name":"car", "verb":"entered", "frame":526},
{"name":"car", "verb":"entered", "frame":529},
{"name":"car", "verb":"exited", "frame":536},
{"name":"car", "verb":"entered", "frame":537},
{"name":"car", "verb":"entered", "frame":539},
{"name":"car", "verb":"exited", "frame":544},
{"name":"car", "verb":"entered", "frame":545},
{"name":"car", "verb":"entered", "frame":553},
{"name":"car", "verb":"exited", "frame":557},
{"name":"car", "verb":"exited", "frame":560},
{"name":"skateboard", "verb":"entered", "frame":561},
{"name":"car", "verb":"entered", "frame":562},
{"name":"car", "verb":"entered", "frame":562},
{"name":"skateboard", "verb":"exited", "frame":562},
{"name":"car", "verb":"entered", "frame":563},
{"name":"car", "verb":"exited", "frame":566},
{"name":"car", "verb":"entered", "frame":569},
{"name":"car", "verb":"exited", "frame":570},
{"name":"car", "verb":"exited", "frame":571},
{"name":"car", "verb":"entered", "frame":582},
{"name":"car", "verb":"exited", "frame":583},
{"name":"car", "verb":"entered", "frame":591},
{"name":"car", "verb":"entered", "frame":591},
{"name":"car", "verb":"exited", "frame":592},
{"name":"car", "verb":"exited", "frame":593},
{"name":"car", "verb":"entered", "frame":596},
{"name":"car", "verb":"exited", "frame":597},
{"name":"car", "verb":"entered", "frame":611},
{"name":"car", "verb":"exited", "frame":612},
{"name":"car", "verb":"entered", "frame":613},
{"name":"car", "verb":"entered", "frame":614},
{"name":"car", "verb":"entered", "frame":616},
{"name":"car", "verb":"entered", "frame":616},
{"name":"car", "verb":"exited", "frame":618},
{"name":"car", "verb":"exited", "frame":622},
{"name":"car", "verb":"entered", "frame":624},
{"name":"car", "verb":"exited", "frame":626},
{"name":"car", "verb":"exited", "frame":626},
{"name":"truck", "verb":"entered", "frame":626},
{"name":"truck", "verb":"exited", "frame":627},
{"name":"truck", "verb":"entered", "frame":629},
{"name":"truck", "verb":"entered", "frame":629},
{"name":"car", "verb":"entered", "frame":630},
{"name":"car", "verb":"exited", "frame":631},
{"name":"car", "verb":"entered", "frame":634},
{"name":"car", "verb":"entered", "frame":637},
{"name":"car", "verb":"exited", "frame":641},
{"name":"car", "verb":"exited", "frame":641},
{"name":"car", "verb":"entered", "frame":642},
{"name":"car", "verb":"exited", "frame":644},
{"name":"car", "verb":"exited", "frame":645},
{"name":"car", "verb":"exited", "frame":645},
{"name":"car", "verb":"entered", "frame":646},
{"name":"car", "verb":"exited", "frame":647},
{"name":"car", "verb":"entered", "frame":648},
{"name":"car", "verb":"exited", "frame":649},
{"name":"car", "verb":"exited", "frame":650},
{"name":"bus", "verb":"entered", "frame":651},
{"name":"car", "verb":"entered", "frame":651},
{"name":"car", "verb":"entered", "frame":652},
{"name":"bus", "verb":"exited", "frame":652},
{"name":"car", "verb":"entered", "frame":654},
{"name":"car", "verb":"exited", "frame":655},
{"name":"car", "verb":"entered", "frame":657},
{"name":"car", "verb":"entered", "frame":658},
{"name":"car", "verb":"exited", "frame":659},
{"name":"car", "verb":"exited", "frame":661},
{"name":"car", "verb":"exited", "frame":663},
{"name":"car", "verb":"entered", "frame":666},
{"name":"car", "verb":"entered", "frame":669},
{"name":"car", "verb":"entered", "frame":669},
{"name":"car", "verb":"exited", "frame":670},
{"name":"car", "verb":"entered", "frame":671},
{"name":"truck", "verb":"exited", "frame":672},
{"name":"car", "verb":"entered", "frame":675},
{"name":"car", "verb":"entered", "frame":675},
{"name":"truck", "verb":"entered", "frame":675},
{"name":"car", "verb":"exited", "frame":676},
{"name":"truck", "verb":"exited", "frame":676},
{"name":"car", "verb":"exited", "frame":677},
{"name":"truck", "verb":"entered", "frame":677},
{"name":"car", "verb":"entered", "frame":678},
{"name":"truck", "verb":"entered", "frame":679},
{"name":"car", "verb":"exited", "frame":680},
{"name":"car", "verb":"entered", "frame":681},
{"name":"car", "verb":"exited", "frame":682},
{"name":"car", "verb":"exited", "frame":682},
{"name":"truck", "verb":"exited", "frame":683},
{"name":"car", "verb":"entered", "frame":684},
{"name":"car", "verb":"entered", "frame":684},
{"name":"truck", "verb":"entered", "frame":684},
{"name":"car", "verb":"exited", "frame":685},
{"name":"car", "verb":"exited", "frame":685},
{"name":"truck", "verb":"exited", "frame":685},
{"name":"car", "verb":"entered", "frame":686},
{"name":"truck", "verb":"entered", "frame":686},
{"name":"car", "verb":"entered", "frame":687},
{"name":"truck", "verb":"exited", "frame":687},
{"name":"truck", "verb":"entered", "frame":688},
{"name":"car", "verb":"exited", "frame":689},
{"name":"truck", "verb":"entered", "frame":689},
{"name":"car", "verb":"entered", "frame":690},
{"name":"truck", "verb":"exited", "frame":690},
{"name":"car", "verb":"exited", "frame":692},
{"name":"car", "verb":"exited", "frame":692},
{"name":"truck", "verb":"entered", "frame":692},
{"name":"truck", "verb":"exited", "frame":694},
{"name":"truck", "verb":"exited", "frame":696},
{"name":"car", "verb":"exited", "frame":697},
{"name":"car", "verb":"entered", "frame":698},
{"name":"car", "verb":"entered", "frame":699},
{"name":"truck", "verb":"exited", "frame":699},
{"name":"car", "verb":"entered", "frame":702},
{"name":"truck", "verb":"entered", "frame":702},
{"name":"truck", "verb":"exited", "frame":703},
{"name":"truck", "verb":"exited", "frame":704},
{"name":"truck", "verb":"entered", "frame":705},
{"name":"car", "verb":"exited", "frame":706},
{"name":"truck", "verb":"exited", "frame":706},
{"name":"car", "verb":"entered", "frame":707},
{"name":"truck", "verb":"entered", "frame":707},
{"name":"car", "verb":"exited", "frame":708},
{"name":"car", "verb":"entered", "frame":709},
{"name":"truck", "verb":"exited", "frame":709},
{"name":"car", "verb":"exited", "frame":710},
{"name":"car", "verb":"entered", "frame":711},
{"name":"truck", "verb":"entered", "frame":712},
{"name":"truck", "verb":"entered", "frame":712},
{"name":"truck", "verb":"exited", "frame":714},
{"name":"car", "verb":"exited", "frame":716},
{"name":"car", "verb":"entered", "frame":718},
{"name":"car", "verb":"entered", "frame":720},
{"name":"car", "verb":"entered", "frame":722},
{"name":"car", "verb":"exited", "frame":724},
{"name":"car", "verb":"entered", "frame":728},
{"name":"car", "verb":"exited", "frame":729},
{"name":"truck", "verb":"exited", "frame":731},
{"name":"car", "verb":"entered", "frame":734},
{"name":"car", "verb":"exited", "frame":735},
{"name":"car", "verb":"exited", "frame":735},
{"name":"truck", "verb":"entered", "frame":735},
{"name":"car", "verb":"entered", "frame":736},
{"name":"truck", "verb":"exited", "frame":736},
{"name":"car", "verb":"exited", "frame":737},
{"name":"truck", "verb":"entered", "frame":737},
{"name":"car", "verb":"entered", "frame":738},
{"name":"car", "verb":"exited", "frame":739},
{"name":"car", "verb":"entered", "frame":740},
{"name":"truck", "verb":"entered", "frame":740},
{"name":"car", "verb":"entered", "frame":741},
{"name":"truck", "verb":"exited", "frame":741},
{"name":"truck", "verb":"exited", "frame":741},
{"name":"car", "verb":"entered", "frame":742},
{"name":"car", "verb":"exited", "frame":744},
{"name":"car", "verb":"exited", "frame":745},
{"name":"car", "verb":"entered", "frame":746},
{"name":"truck", "verb":"entered", "frame":747},
{"name":"car", "verb":"exited", "frame":749},
{"name":"truck", "verb":"entered", "frame":749},
{"name":"truck", "verb":"exited", "frame":750},
{"name":"truck", "verb":"exited", "frame":750},
{"name":"car", "verb":"exited", "frame":752},
{"name":"truck", "verb":"entered", "frame":754},
{"name":"car", "verb":"exited", "frame":755},
{"name":"car", "verb":"entered", "frame":757},
{"name":"truck", "verb":"exited", "frame":757},
{"name":"car", "verb":"entered", "frame":758},
{"name":"car", "verb":"exited", "frame":759},
{"name":"car", "verb":"exited", "frame":760},
{"name":"car", "verb":"exited", "frame":760},
{"name":"car", "verb":"entered", "frame":761},
{"name":"car", "verb":"entered", "frame":762},
{"name":"car", "verb":"exited", "frame":763},
{"name":"car", "verb":"exited", "frame":767},
{"name":"car", "verb":"exited", "frame":767},
{"name":"car", "verb":"entered", "frame":768},
{"name":"car", "verb":"entered", "frame":768},
{"name":"car", "verb":"exited", "frame":769},
{"name":"car", "verb":"entered", "frame":770},
{"name":"car", "verb":"exited", "frame":772},
{"name":"car", "verb":"entered", "frame":774},
{"name":"car", "verb":"entered", "frame":777},
{"name":"car", "verb":"exited", "frame":778},
{"name":"car", "verb":"entered", "frame":780},
{"name":"car", "verb":"exited", "frame":786},
{"name":"car", "verb":"exited", "frame":786},
{"name":"car", "verb":"entered", "frame":787},
{"name":"car", "verb":"entered", "frame":787},
{"name":"car", "verb":"entered", "frame":787},
{"name":"car", "verb":"exited", "frame":788},
{"name":"car", "verb":"exited", "frame":789},
{"name":"car", "verb":"exited", "frame":789},
{"name":"car", "verb":"entered", "frame":790},
{"name":"car", "verb":"exited", "frame":792},
{"name":"car", "verb":"exited", "frame":792},
{"name":"car", "verb":"entered", "frame":794},
{"name":"car", "verb":"entered", "frame":794},
{"name":"car", "verb":"entered", "frame":796},
{"name":"car", "verb":"exited", "frame":797},
{"name":"car", "verb":"exited", "frame":797},
{"name":"car", "verb":"entered", "frame":798},
{"name":"car", "verb":"entered", "frame":798},
{"name":"car", "verb":"entered", "frame":799},
{"name":"car", "verb":"exited", "frame":800},
{"name":"car", "verb":"entered", "frame":802},
{"name":"car", "verb":"exited", "frame":804},
{"name":"car", "verb":"entered", "frame":805},
{"name":"car", "verb":"exited", "frame":806},
{"name":"car", "verb":"exited", "frame":806},
{"name":"car", "verb":"entered", "frame":810},
{"name":"car", "verb":"entered", "frame":810},
{"name":"car", "verb":"exited", "frame":811},
{"name":"car", "verb":"exited", "frame":811},
{"name":"car", "verb":"exited", "frame":811},
{"name":"car", "verb":"exited", "frame":811},
{"name":"car", "verb":"entered", "frame":812},
{"name":"car", "verb":"entered", "frame":813},
{"name":"car", "verb":"entered", "frame":816},
{"name":"car", "verb":"exited", "frame":817},
{"name":"car", "verb":"exited", "frame":817},
{"name":"car", "verb":"entered", "frame":820},
{"name":"car", "verb":"exited", "frame":821},
{"name":"car", "verb":"entered", "frame":824},
{"name":"car", "verb":"exited", "frame":827},
{"name":"car", "verb":"entered", "frame":828},
{"name":"car", "verb":"exited", "frame":829},
{"name":"car", "verb":"entered", "frame":830},
{"name":"car", "verb":"entered", "frame":830},
{"name":"car", "verb":"exited", "frame":832},
{"name":"car", "verb":"entered", "frame":833},
{"name":"car", "verb":"exited", "frame":835},
{"name":"car", "verb":"entered", "frame":836},
{"name":"car", "verb":"exited", "frame":837},
{"name":"person", "verb":"entered", "frame":837},
{"name":"car", "verb":"exited", "frame":838},
{"name":"person", "verb":"exited", "frame":838},
{"name":"person", "verb":"entered", "frame":843},
{"name":"car", "verb":"exited", "frame":844},
{"name":"person", "verb":"exited", "frame":844},
{"name":"car", "verb":"exited", "frame":845},
{"name":"car", "verb":"entered", "frame":846},
{"name":"car", "verb":"entered", "frame":846},
{"name":"car", "verb":"exited", "frame":847},
{"name":"car", "verb":"exited", "frame":847},
{"name":"car", "verb":"exited", "frame":847},
{"name":"car", "verb":"exited", "frame":847},
{"name":"car", "verb":"entered", "frame":848},
{"name":"car", "verb":"entered", "frame":848},
{"name":"car", "verb":"entered", "frame":849},
{"name":"car", "verb":"entered", "frame":851},
{"name":"motorbike", "verb":"entered", "frame":852},
{"name":"car", "verb":"exited", "frame":853},
{"name":"motorbike", "verb":"exited", "frame":854},
{"name":"car", "verb":"entered", "frame":855},
{"name":"car", "verb":"entered", "frame":856},
{"name":"car", "verb":"exited", "frame":857},
{"name":"car", "verb":"exited", "frame":857},
{"name":"car", "verb":"entered", "frame":858},
{"name":"car", "verb":"entered", "frame":858},
{"name":"car", "verb":"exited", "frame":860},
{"name":"car", "verb":"exited", "frame":864},
{"name":"car", "verb":"exited", "frame":864},
{"name":"car", "verb":"entered", "frame":867},
{"name":"car", "verb":"entered", "frame":869},
{"name":"car", "verb":"exited", "frame":871},
{"name":"car", "verb":"entered", "frame":872},
{"name":"car", "verb":"exited", "frame":876},
{"name":"motorbike", "verb":"entered", "frame":878},
{"name":"motorbike", "verb":"exited", "frame":881},
{"name":"car", "verb":"exited", "frame":883},
{"name":"motorbike", "verb":"entered", "frame":884},
{"name":"car", "verb":"entered", "frame":888},
{"name":"car", "verb":"exited", "frame":890},
{"name":"car", "verb":"entered", "frame":891},
{"name":"motorbike", "verb":"exited", "frame":891},
{"name":"car", "verb":"exited", "frame":892},
{"name":"motorbike", "verb":"entered", "frame":901},
{"name":"car", "verb":"exited", "frame":903},
{"name":"person", "verb":"entered", "frame":905},
{"name":"car", "verb":"entered", "frame":907},
{"name":"person", "verb":"exited", "frame":907},
{"name":"motorbike", "verb":"entered", "frame":909},
{"name":"person", "verb":"entered", "frame":909},
{"name":"car", "verb":"exited", "frame":910},
{"name":"car", "verb":"entered", "frame":912},
{"name":"car", "verb":"entered", "frame":912},
{"name":"car", "verb":"exited", "frame":914},
{"name":"person", "verb":"exited", "frame":916},
{"name":"car", "verb":"entered", "frame":918},
{"name":"car", "verb":"exited", "frame":919},
{"name":"car", "verb":"entered", "frame":920},
{"name":"motorbike", "verb":"exited", "frame":920},
{"name":"car", "verb":"exited", "frame":921},
{"name":"car", "verb":"exited", "frame":921},
{"name":"motorbike", "verb":"exited", "frame":921},
{"name":"car", "verb":"entered", "frame":922},
{"name":"motorbike", "verb":"entered", "frame":922},
{"name":"motorbike", "verb":"exited", "frame":924},
{"name":"car", "verb":"entered", "frame":925},
{"name":"car", "verb":"exited", "frame":926},
{"name":"car", "verb":"entered", "frame":927},
{"name":"car", "verb":"entered", "frame":927},
{"name":"car", "verb":"exited", "frame":928},
{"name":"car", "verb":"entered", "frame":932},
{"name":"car", "verb":"exited", "frame":937},
{"name":"car", "verb":"entered", "frame":942},
{"name":"car", "verb":"exited", "frame":944},
{"name":"truck", "verb":"entered", "frame":944},
{"name":"truck", "verb":"entered", "frame":945},
{"name":"car", "verb":"entered", "frame":946},
{"name":"car", "verb":"entered", "frame":946},
{"name":"truck", "verb":"exited", "frame":946},
{"name":"truck", "verb":"exited", "frame":946},
{"name":"motorbike", "verb":"entered", "frame":949},
{"name":"car", "verb":"entered", "frame":950}]


function search() {
  // gdata = null
  var input = document.getElementById("search").value
  var table = document.getElementById("sidePane");
  // console.log(input)

  results = []
  for(var i = 0; i < data.length-1; i++) {
    if(input == data[i].name || input == data[i].verb || input == data[i].frame) {
      results.push(data[i])
    }
  }
  populateSideWindows(results)
}




function populateSideWindows(data) {
  var table = document.getElementById("sidePane");
  var row; 
  for(var i = 0; i < data.length; i++) { //all events
      fps = 29.97;
      objectName = data[i].name;
      entOrExit = data[i].verb;
      frameNumber = data[i].frame;
      time = frameNumber/fps;
      console.log(objectName)

      row = table.insertRow();
      row.outerHTML = '<tr onclick="jump(time)" class="display"> <td>' + objectName + '</td>'
        + '<td>' + entOrExit + '</td>' + '<td>' + time + '</td> </tr>';
      
  }
}



var isPlaying = false; //true --> is playing

function togglePlay() {
  isPlaying = !isPlaying;
  var player = document.getElementById('video_player');

  populateSideWindows(data)

  if(isPlaying) {
    player.play();
    document.getElementById("play_button").outerHTML = '<img src="GUI/pause.jpg" width="25" height="25" onclick="togglePlay()"  id="play_button"></img> '
  }
  else {
    player.pause();
    document.getElementById("play_button").outerHTML = '<img src="GUI/play.jpg" width="25" height="25" onclick="togglePlay()"  id="play_button"></img> '
  }
}

function jump(time) {
  var player = document.getElementById("video_player");
  player.currentTime=time
}

if (document.readyState === "complete") {
  console.log("test")
}

